
type: "diff_drive_controller/DiffDriveController"
publish_rate: 50  # Publish rate for the controller (Hz)

left_wheel: ['left_wheel_joint']  # Name of the left wheel joint
right_wheel: ['right_wheel_joint']  # Name of the right wheel joint

wheel_separation: 0.4  # Distance between the wheels (meters)
wheel_radius: 0.0964415 #wheel radius

pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # Pose covariance
twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # Twist covariance

base_frame_id: "base_link"  # Base frame ID

linear:
  x:
    has_velocity_limits: true
    max_velocity: 0.2  # (m/s)
    has_acceleration_limits: true
    max_acceleration: 0.6  #  (m/s^2)

angular:
  z:
    has_velocity_limits: true
    max_velocity: 2.0  #(rad/s)
    has_acceleration_limits: true
    max_acceleration: 6.0  #  (rad/s^2)



